// flow-typed signature: 2f25605263743e2bd71575c28731757a
// flow-typed version: <<STUB>>/babel-plugin-import_v^1.12.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-import/lib' {
  declare module.exports: any;
}

declare module 'babel-plugin-import/lib/Plugin' {
  declare module.exports: any;
}

declare module 'babel-plugin-import/src' {
  declare module.exports: any;
}

declare module 'babel-plugin-import/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-import/lib/index' {
  declare module.exports: $Exports<'babel-plugin-import/lib'>;
}
declare module 'babel-plugin-import/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-import/lib'>;
}
declare module 'babel-plugin-import/lib/Plugin.js' {
  declare module.exports: $Exports<'babel-plugin-import/lib/Plugin'>;
}
declare module 'babel-plugin-import/src/index' {
  declare module.exports: $Exports<'babel-plugin-import/src'>;
}
declare module 'babel-plugin-import/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-import/src'>;
}
declare module 'babel-plugin-import/src/Plugin.js' {
  declare module.exports: $Exports<'babel-plugin-import/src/Plugin'>;
}
